### ISSUE TITLE
Lambda versioning

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cumulus#1013]
The information in the docs for Lambda versioning is incorrect:
https://github.com/nasa/cumulus/blob/master/docs/lambda_versioning.md

In that there is no supported field `uniqueIdentifier` under `s2Source` for Lambdas, and instead an error will be thrown if provided.

I'm not sure if that means the rest of the document is still relevant, does the versioning still happen like described here?  Does it use the s3Source `key` field instead as an identifier?

**Comment by Jkovarik** [comment]
The uniqueIdentifer field is, or should be supported under `s3source`.  We're using it in our example/integration deployments here: https://github.com/nasa/cumulus/blob/master/example/lambdas.yml, for example.

**Comment by matthewhanson** [comment]
Ok, the error I thought was just "uniqueIdentifier" not supported, but it could have been complaining about me not abiding by the restrictions for that key. I'll test this again tomorrow and report back.   Thanks for the response!

**Comment by matthewhanson** [comment]
This works, thanks @Jkovarik and sorry for the confusion.

**Comment by Jkovarik** [comment]
Awesome!  Happy to help.
