### ISSUE TITLE
feat(audit): Update audit-ci to v2.0.1 and re-enable audit-ci in the pipeline

### ISSUE THREAD

**Issue by quinnturner** [nasa/cumulus#1040]
NPM's server response with ENOAUDIT has been frustrating for the `audit-ci` project, random failures have unnecessarily halted CI environments.

The recent `v2.0.1` [release](https://github.com/IBM/audit-ci/releases/tag/v2.0.1) ([Diff](https://github.com/IBM/audit-ci/compare/v2.0.0..v2.0.1)) should fix the retry mechanism for NPM, addressing failures in your pipeline (ex: https://travis-ci.org/nasa/cumulus/jobs/531849256).

`v2.0.0` is a major release ([CHANGELOG](https://github.com/IBM/audit-ci/releases/tag/v2.0.0)) with soft breaking changes (only deprecation warnings). Your report will look slightly different since it will show "important" info rather than just the "summary" (significant improvement IMO).

I have investigated your `audit-ci.json` file and there are **no actions required** other than updating to `v2.0.1` and uncommenting the job in Travis.

**Comment by Jkovarik** [comment]
Merged to master https://github.com/nasa/cumulus/pull/1042
