### ISSUE TITLE
Insufficient logging detail when timing out retrieving OAuth tokens

### ISSUE THREAD

**Issue by garysieling** [nasa/cumulus#1043]
I saw an event where for some time we were unable to complete the OAuth token handeshake due to a timeout somewhere in the system.

You can see that it timed out ("Task timed out after 20.02 seconds"), but there is no stack trace or indication of what what it was doing that timed out (waiting for some URL?), which makes this difficult to triage.

Here are example logs:

19:13:55
[06/Jun/2019:19:13:55 +0000] "GET /token?state=https%3A%2F%2Fd3sxx7zkzigde1.cloudfront.net%2F%23%2Fauth HTTP/1.1"307 11 "https://d3sxx7zkzigde1.cloudfront.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" -

19:13:55
END RequestId: 86e097d4-90ac-4fa6-9c40-92586125f011

19:13:55
REPORT RequestId: 86e097d4-90ac-4fa6-9c40-92586125f011	Duration: 95.12 ms	Billed Duration: 100 ms Memory Size: 512 MB	Max Memory Used: 512 MB

19:13:59
START RequestId: 864f7a3d-0f2c-4c08-83aa-b41684e8cea7 Version: $LATEST

19:14:19
END RequestId: 864f7a3d-0f2c-4c08-83aa-b41684e8cea7

19:14:19
REPORT RequestId: 864f7a3d-0f2c-4c08-83aa-b41684e8cea7	Duration: 20020.32 ms	Billed Duration: 20000 ms Memory Size: 512 MB	Max Memory Used: 512 MB

19:14:19
2019-06-06T19:14:19.346Z 864f7a3d-0f2c-4c08-83aa-b41684e8cea7 Task timed out after 20.02 seconds
2019-06-06T19:14:19.346Z 864f7a3d-0f2c-4c08-83aa-b41684e8cea7 Task timed out after 20.02 seconds

**Comment by garysieling** [comment]
Ok, I realize after further inspection that the "Task timed out after..." message comes from AWS Lambda, not Cumulus, but still it would be helpful if there was information in the logs you could use to trace this.

**Comment by markdboyd** [comment]
@garysieling Sorry for the delayed response here. Can you help me understand what additional logging would be helpful here?

Also, just looking at the logs you posted, it seems like the Lambda invocation that timed out is not the same one that was doing the Oauth token handshake. And weirdly, the Lambda invocation that timed out didn't log any API request information, which every request to that Lambda should do.

**Comment by garysieling** [comment]
I was looking to see API calls out from the lambda - assuming that's what's timing out, I'd like to see a URL or service it's calling. If that's something that's supposed to be there, it's possible I have something misconfigured with logging. .

**Comment by markdboyd** [comment]
This lambda is used to handle requests to our API gateway via Express. [Based on how we have it configured](https://github.com/nasa/cumulus/blob/master/packages/api/app/index.js#L31), the first thing it should always log is something like this indicating what route it is trying to request:

```
[06/Jun/2019:19:13:55 +0000] "GET /token?state=https%3A%2F%2Fd3sxx7zkzigde1.cloudfront.net%2F%23%2Fauth HTTP/1.1"307 11 "https://d3sxx7zkzigde1.cloudfront.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36" -
```

If it doesn't do that, then I assume it is timing out in [the code that is passing the Lambda event on to Express](https://github.com/nasa/cumulus/blob/master/packages/api/app/index.js#L58). I'm not sure what additional logging we could add to clarify what is happening there. 

Is still happening for you?

**Comment by markdboyd** [comment]
@garysieling Would the work on #1099 be sufficient to close this out?

**Comment by garysieling** [comment]
Yeah, that works for me. We are finding that you need to do more with x-ray than just turn it on to get the full value, but I'll just send another PR if necessary.
