### ISSUE TITLE
Documentation references non-public site

### ISSUE THREAD

**Issue by garysieling** [nasa/cumulus#1066]
These two pages refer you to the Earthdata wiki:

https://nasa.github.io/cumulus/docs/system-documentation/system-documentation
https://nasa.github.io/cumulus/docs/operator-docs/lifecycle-policies

Would it be possible for someone with appropriate access to copy over the relevant information from that wiki?

Thanks.

**Comment by markdboyd** [comment]
@garysieling The Earthdata wiki links for system documentation literally just repeat what the docs already say, so those should be removed. And the link from the lifecycle policies page just gives a lot of context into the storage decisions for Cumulus that isn't necessary, but I'm not sure what our options are there. I can check with the team.

**Comment by garysieling** [comment]
Great, thanks for looking into it!
