### ISSUE TITLE
Timeout in bootstrap lambda

### ISSUE THREAD

**Issue by garysieling** [nasa/cumulus#1073]
I'm getting a timeout in the bootstrap lambda. This is most likely an environment issue on our side, that I'm debugging.

The log message we get does not have the full stack trace for the primary issue. I.e. you can't tell which of the bootstrap operations is failing, though it is likely connecting to one of DynamoDB or Elasticsearch.

All of these functions except the dynamodb one are use async/await, so it may be that if that function was async you'd get more - once I confirm that this is the case I'll file a PR.
```bootstrapElasticSearch(get(es, 'host')),
    bootstrapUsers(get(users, 'table'), get(users, 'records')),
    bootstrapCmrProvider(get(cmr, 'Password')),
    bootstrapDynamoDbTables(dynamos)
```

Here are the logs:
```
{
    "error": {
        "name": "Error",
        "message": "Request Timeout after 50000ms",
        "stack": [
            "Error: Request Timeout after 50000ms",
            "    at /var/task/index.js:288620:15",
            "    at Timeout.<anonymous> (/var/task/index.js:288649:7)",
            "    at ontimeout (timers.js:482:11)",
            "    at tryOnTimeout (timers.js:317:5)",
            "    at Timer.listOnTimeout (timers.js:277:5)"
        ]
    },
    "level": "error",
    "message": "Request Timeout after 50000ms",
    "sender": "unknown",
    "timestamp": "2019-06-26T18:36:30.965Z"
}

{
    "level": "info",
    "message": "RESPONSE BODY:\n {\"Status\":\"SUCCESS\",\"PhysicalResourceId\":\"cumulus-bootstraping-daac-ops-api-deployment\",\"StackId\":\"arn:aws:cloudformation:us-west-2:---:stack/pipe-sit/f43602a0-9840-11e9-ad97-06972e890616\",\"RequestId\":\"a0f360cb-17e9-4d39-a0a5-f96deb39642d\",\"LogicalResourceId\":\"CumulusCustomResource\",\"Data\":null}",
    "sender": "unknown",
    "timestamp": "2019-06-26T18:36:45.829Z"
}```

**Comment by garysieling** [comment]
Upon further investigation, the task timing out was connecting to the Elasticsearch index, and it turns out the error "Request Timeout after 50000ms" is unique to the internals of the Elasticsearch client.  Knowing where the error is I'm fine to close this ticket.  It's not clear to me how this could be easily improved since the error is buried in a dependency. 

In case anyone runs across this or a similar problem, here is how I found the answer:
# Commit the Cumulus node_modules packages to our repo
# Open @cumulus/api/dist/bootstrap/index.js
# Search for "Request Timeout after "
# Change the error message to include the URL: "respond(new errors.RequestTimeout('Request Timeout after ' + requestTimeout        + 'ms to ' + connection.host.makeUrl(params.req)));"
# Redeploy and look at the logs. 

I'm not certain why the stack trace doesn't include anything from the bootstrap lambda - the async/await looks right, and I thought it was support to cover this.

**Comment by hyoklee** [comment]
@garysieling, I have a similar problem. Can you explain how you resolved it?

**Comment by garysieling** [comment]
Yes, my specific issue was a security group that limited the traffic from the lambda to Elasticsearch too much.

I made a lambda the does HTTP requests and set it up to use the same settings (VPC / IAM role) as the lambda that CumulusCustomResource uses, then changed network settings until that worked.

I wrote up some documentation and an example lambda you can use here: https://www.garysieling.com/blog/debugging-aws-services-with-lambda

**Comment by hyoklee** [comment]
@garysieling, do you mean HTTPS, not HTTP? Would you please elaborate on the network setting change? CUMULUS deployment documentation should cover this, not your personal blog. 

Thus, would you please reopen this ticket? Default CUMULUS ElasticSearch setting and lambda in template cannot be deployed.

**Comment by garysieling** [comment]
I'm working with a customized installation of Cumulus (I'm not on the Cumulus team). The root cause was caused by something we did, not to Cumulus - this ticket was just about how to debug the issue. If there is an issue with one of the defaults I would suggest opening a new ticket.
