### ISSUE TITLE
Elasticsearch Capacity

### ISSUE THREAD

**Issue by garysieling** [nasa/cumulus#1091]
Can you provide any guidance on the size and number of nodes required to run a production Cumulus Elasticsearch cluster?

**Comment by laurenfrederick** [comment]
Hi @garysieling, I talked to some of our DAACs who will be going operational. 

For a DAAC less than 100TB they are using m4.large.elasticsearch with a volume size of 100 and probably 3 instances. Another DAAC i asked who is not quite at that point was also planning on 3 instances.

**Comment by garysieling** [comment]
Great, thanks!
