### ISSUE TITLE
Disable ElasticSearch-related lambda function deployment when es:null is specified in config.yml.

### ISSUE THREAD

**Issue by hyoklee** [nasa/cumulus#1108]

**Comment by markdboyd** [comment]
Kes deployment is no longer supported for Cumulus. Elasticsearch based functionality can be disabled for Cumulus using the [`include_elasticsearch` variable to the `data-persistence` module](https://github.com/nasa/cumulus/blob/a651ddf9eb9fc919d5e5c1b3f474106ef58325ea/tf-modules/data-persistence/variables.tf#L59)
