### ISSUE TITLE
Enable point in time backups on new tables

### ISSUE THREAD

**Issue by garysieling** [nasa/cumulus#1116]
I see the following comment, and experienced the behavior as described by it:

`**Imoprtant Note:** Configuring point-in-time recovery is not supported by the CloudFormation (as of June 2018). We enable this feature deployment using AWS API. However, due to a limitation of AWS API, the feature fails to be enabled if it is running against newly created tables.`

This is no longer true - you can do the following in Cloudformation:

> PointInTimeRecoverySpecification:
>      PointInTimeRecoveryEnabled: true

**Comment by garysieling** [comment]
In case anyone needs this, I worked around it by adding a script after Cumulus deploys:

`

TABLES=("pipe-${ENVIRONMENT}-AccessTokensTable" \
        "pipe-${ENVIRONMENT}-AsyncOperationsTable" \
        "pipe-${ENVIRONMENT}-CollectionsTable" \
        "pipe-${ENVIRONMENT}-ExecutionsTable" \
        "pipe-${ENVIRONMENT}-FilesTable" \
        "pipe-${ENVIRONMENT}-GranulesTable" \
        "pipe-${ENVIRONMENT}-PdrsTable" \
        "pipe-${ENVIRONMENT}-ProvidersTable" \
        "pipe-${ENVIRONMENT}-RulesTable" \
        "pipe-${ENVIRONMENT}-SemaphoresTable" \
        "pipe-${ENVIRONMENT}-UsersTable")

for table in "${TABLES[@]}"; do
    aws dynamodb update-continuous-backups --table-name ${table} --point-in-time-recovery-specification PointInTimeRecoveryEnabled=true
done`

**Comment by laurenfrederick** [comment]
Hey @garysieling we're currently doing a migration from kes to terraform and I've made sure to note this support as an acceptance criteria for those tickets. We expect to have at least a partial migration done by end of September.

Thank you for the script!

**Comment by garysieling** [comment]
Sounds good!

**Comment by markdboyd** [comment]
@garysieling As part of the new Terraform-based deployment for Cumulus, you can specify the DynamoDb tables that you want to have point-in-time backup enabled on:

https://github.com/nasa/cumulus/blob/master/tf-modules/data-persistence/variables.tf#L38

So I'm going to close this issue, but feel free to re-open if you need further assistance
