### ISSUE TITLE
Remove all NGAP dependencies in default documentation and code.

### ISSUE THREAD

**Issue by hyoklee** [nasa/cumulus#1138]
For example, the following paragraph in [1] bothers me:

```
Also note, if you dont specify the amiid, it will try to use a default, which may or may not exist. The default AMI is an NGAP-approved AMI. The most recent NGAP AMI can be found using these instructions.
```

I wish CUMULUS is for non-NGAP users by default. 

[1] https://nasa.github.io/cumulus/docs/deployment/config_descriptions

**Comment by bilts** [comment]
The prioritization of EOSDIS users is unlikely to change in the near future, so we will continue to make NGAP the easy path.  If our NGAP use causes actual issues for non-EOSDIS use, other than needing to set non-default values, we’d like to hear those.

We would further gladly accept PRs that accomplished the goal of easing non-EOSDIS adoption while not compromising the ease of use for EOSDIS users, but the team cannot prioritize such work at this time.
