### ISSUE TITLE
Cumulus & Data-Persistence: Add ability to choose lifecycle.prevent_destroy property

### ISSUE THREAD

**Issue by kbeamnsidc** [nasa/cumulus#1440]
In a development, integration, testing environment, it's often useful to spin up and tear down an entire cumulus stack. Currently the lifecycle.prevent_destroy is set to true in data-persistence. This feature would add the ability to choose the prevent_destroy value for a stack, so that it's easy to teardown an entire stack in an environment, but to prevent destruction in a production / quasi-production environment.

**Comment by nemreid** [comment]
Hi @kbeamnsidc, just wanted to update you on this issue: Terraform does not allow `prevent_destroy` to be set dynamically. See https://github.com/hashicorp/terraform/issues/3116 
We've yet to find a suitable answer to this problem, but any updates will be filed to CUMULUS-1744 in our JIRA project.

**Comment by markdboyd** [comment]
As @nemreid said, it's currently not possible to support this request. In the meantime you can follow this guide on how to teardown everything including Dynamo tables:

https://nasa.github.io/cumulus/docs/deployment/terraform-best-practices#how-to-destroy-everything

Going to close this issue but feel free to re-open if you need further assistance
