### ISSUE TITLE
An update to the `buckets` object in `variables.tf` doesn't update the `workflow_template.json` file in S3

### ISSUE THREAD

**Issue by ifestus** [nasa/cumulus#1467]
**Summary:** 
_in the context of cumulus-tf/_
We have an existing deployment of Cumulus with some number of buckets. We wanted to add an additional bucket for custom uses. The steps I followed were: create the bucket, update the `buckets` variable in `terraform.tfvars` with that new bucket information, and re-deploy.

After re-deploying, I attempted to run a workflow that makes use of this new `bucket` value in the Cumulus message (`meta.buckets.glacier`), but the new bucket doesn't exist in that `buckets` object and my workflow fails.

I did some digging and it appears that the `workflow_template.json` file at `${internal}/${prefix}/workflow_template.json` was not updated by my deployment. I was able to hack past this by manually updating this file to have my desired `bucket` object.

**Reproduction:**
Starting with a deployment that has some `buckets` object:

```
buckets = {
  internal = {
    name = "prefix-internal"
    type = "internal"
  }
  private = {
    name = "prefix-private"
    type = "private"
  },
  protected = {
    name = "prefix-protected"
    type = "protected"
  },
  public = {
    name = "prefix-public"
    type = "public"
  }
}
```

Update the `buckets` object to have a _new additional_ bucket and deploy:

```
buckets = {
...
  glacier = {
    name = "prefix-glacier"
    type = "private"
  }
}
```

Check the `workflow_template.json` file at `${internal-bucket}/${prefix}/workflow_template.json`. For me, this file isn't updated - there is no `glacier` bucket in the `meta.buckets` attribute.

**Comment by yjpa7145** [comment]
I just tried to reproduce this against master (and `cumulus-tf`) but was unable to reproduce. I deployed, added a bucket to my buckets input variable, redeployed, and the new bucket was present in the generated `workflow_template.json`.

@ifestus I'm happy to work with you today to figure out what's going on.

**Comment by ifestus** [comment]
After some additional testing it looks like the reason this value wasn't being updated on my deployment was because there was something on the deployment machine that was silently stopping the `bootstrap` from running correctly.

Thank you @yjpa7145 for attempting to reproduce the error and my apologies for the mistake.
