### ISSUE TITLE
docs/README.md contains broken links

### ISSUE THREAD

**Issue by stark525** [nasa/cumulus#2231]
A few of the links under https://github.com/nasa/cumulus/blob/master/CONTRIBUTING.md are relative paths that do not contain the .md suffix. This leads to 404s when attempting to navigate to them in GitHub.

**Comment by AdvaitDhingra** [comment]
Which links do you mean? All of them seem fine to me.

**Comment by npauzenga** [comment]
Yup! Closing this issue as the associated PR was merged. https://github.com/nasa/cumulus/pull/2257
