### ISSUE TITLE
Allow aws_ecs_task_definition to have a configurable healthcheck

### ISSUE THREAD

**Issue by Michaellh0079** [nasa/cumulus#3351]
Currently it is not possible to configure the `healthcheck `of tasks that use the `cumulus_ecs_service` module.

**Comment by npauzenga** [comment]
Closing this issue as we typically don't track feature requests outside of Jira. Please feel free to create a Jira ticket with more details if this is still relevant/requested.

**Comment by Michaellh0079** [comment]
Just an FYI, this was actually handled in jira actions https://github.com/nasa/cumulus/pull/3353 references this GHRC and Cumulus tickets.
