### ISSUE TITLE
MoveGranules documentation is incorrect for task config `bucket`

### ISSUE THREAD

**Issue by mattp0** [nasa/cumulus#3382]
It describes requiring a bucket that contains a public and private key for CMR. But the code is using this bucket as the sourceBucket to pull the data from. 
https://github.com/nasa/cumulus/blob/master/tasks/move-granules/schemas/config.json#L14 
https://github.com/nasa/cumulus/blob/master/tasks/move-granules/README.md?plain=1#L15
https://github.com/nasa/cumulus/blob/master/tasks/move-granules/index.js#L244
https://github.com/nasa/cumulus/blob/master/tasks/move-granules/index.js#LL294C3-L294C3 #config.bucket being passed to `moveFilesForAllGranules`
https://github.com/nasa/cumulus/blob/master/tasks/move-granules/index.js#L214 # second param is for `sourceBucket`

Putting the wrong bucket in results in a non descriptive error:
```
{\"errorType\":\"TypeError\",\"errorMessage\":\"Function has non-object prototype 'undefined' in instanceof check\",\"trace\":[\"TypeError: Function has non-object prototype 'undefined' in instanceof check\",\"    at Function.[Symbol.hasInstance] (<anonymous>)\",\"    at Object.waitForObjectToExist (/var/task/webpack:/src/S3.ts:228:14)\",\"    at runNextTicks (internal/process/task_queues.js:60:5)\",\"    at listOnTimeout (internal/timers.js:526:9)\",\"    at processTimers (internal/timers.js:500:7)\",\"    at moveFileRequest (/var/task/webpack:/index.js:163:3)\",\"    at async Promise.all (index 0)\",\"    at /var/task/webpack:/index.js:222:24\",\"    at async Promise.all (index 0)\",\"    at moveFilesForAllGranules (/var/task/webpack:/index.js:234:3)\"]}
```

**Comment by jjmccoy** [comment]
Thanks @mattp0. We have submitted a PR for this update: https://bugs.earthdata.nasa.gov/browse/CUMULUS-3345

**Comment by npauzenga** [comment]
Looks like this was resolved in https://github.com/nasa/cumulus/pull/3423. Closing the issue but please create a Jira ticket if this needs further discussion.
