### ISSUE TITLE
Cumulus install failed

### ISSUE THREAD

**Issue by zhudayong1987** [nasa/cumulus#3438]
when I use "npm run bootstrap" install cumulus, I get below error

webpack 5.88.2 compiled with 2 warnings in 11954 ms
lerna ERR! npm run package exited 137 in '@cumulus/db-provision-user-database-lambda'
lerna ERR! npm run package stdout:

> @cumulus/db-provision-user-database-lambda@16.0.0 package
> npm run clean && npm run tsc && npm run webpack && (cd dist/webpack && zip lambda.zip index.js)

> @cumulus/db-provision-user-database-lambda@16.0.0 clean
> rm -rf dist

> @cumulus/db-provision-user-database-lambda@16.0.0 tsc
> ../../node_modules/.bin/tsc

> @cumulus/db-provision-user-database-lambda@16.0.0 webpack
> ../../node_modules/.bin/webpack

lerna ERR! npm run package stderr:
sh: line 1:  8508 Killed                  npm run webpack
lerna ERR! npm run package exited 137 in '@cumulus/db-provision-user-database-lambda'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.

**Comment by zhudayong1987** [comment]
I use centos7,and node v16.19.0

**Comment by etcart** [comment]
working on recreating and investigating

**Comment by etcart** [comment]
I've been unable to recreate this issue as such, although I have encountered issues installing cumulus on centos7, centered around python versioning. can we meet up to discuss this further? I'd like to get more details on your environment to help debug this

**Comment by zhudayong1987** [comment]
### **I used the following command to run it in the vmware virtual machine**

curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
source ~/.bashrc
nvm install 16.19.0
nvm use 16.19.0
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip 
sudo ./aws/install 
./aws/install -i /usr/local/aws-cli -b /usr/local/bin
aws --version
aws configure 
yum -y install openssl-devel zlib-devel gcc
mkdir /usr/local/python3
wget https://www.python.org/ftp/python/3.7.14/Python-3.7.14.tgz
tar -xvf Python-3.7.14.tgz 
cd Python-3.7.14/
./configure --enable-shared --prefix=/usr/local/python3
make -j4
make install
sudo ldconfig /usr/local/python3/lib
ln -s /usr/local/python3/bin/python3 /usr/bin/python3
ln -s /usr/local/python3/bin/pip3 /usr/bin/pip3
pip3 install pipenv
yum install -y docker
systemctl stop firewalld
systemctl disable firewalld
systemctl status firewalld
systemctl start docker
pip3 install -y docker-compose
npm install -g npm@9.8.1
npm install -g lerna
yum install -y git
git clone https://github.com/nasa/cumulus.git
cd cumulus/
mv /usr/bin/python /usr/bin/python_old
mv /usr/bin/python3 /usr/bin/python
npm install
npm run bootstrap

### **But I still get the following error**

[root@localhost cumulus]# npm run bootstrap

> @cumulus/core@1.0.0 bootstrap
> lerna bootstrap --no-ci --force-local && npm run package && git rev-parse --short HEAD > .bootstrapSha

lerna notice cli v5.6.2
lerna info Bootstrapping 70 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle @cumulus/ingest-module@16.0.0~prepublish: @cumulus/ingest-module@16.0.0

> @cumulus/ingest-module@16.0.0 prepublish /home/zdy/Desktop/cumulus/tf-modules/ingest
> node scripts/write-cumulus-version.js

(##################) ⠧ prepublish: sill lifecycle No script for "prepublish" in "@cumulus/cumulus-integration-te
lerna info lifecycle @cumulus/python-process-activity@16.0.0~prepare: @cumulus/python-process-activity@16.0.0

> @cumulus/python-process-activity@16.0.0 prepare /home/zdy/Desktop/cumulus/example/lambdas/python-processing
> npm run build

lerna info lifecycle @cumulus/python-reference-activity@16.0.0~prepare: @cumulus/python-reference-activity@16.0.0

> @cumulus/python-reference-activity@16.0.0 prepare /home/zdy/Desktop/cumulus/example/lambdas/python-reference-activity
> npm run build

lerna info lifecycle @cumulus/python-reference-task@16.0.0~prepare: @cumulus/python-reference-task@16.0.0

> @cumulus/python-reference-task@16.0.0 prepare /home/zdy/Desktop/cumulus/example/lambdas/python-reference-task
> npm run build

lerna info lifecycle @cumulus/example-lib@16.0.0~prepare: @cumulus/example-lib@16.0.0

> @cumulus/example-lib@16.0.0 prepare /home/zdy/Desktop/cumulus/example/scripts/lib
> true

lerna ERR! lifecycle "prepare" errored in "@cumulus/python-process-activity", exiting 127
lerna info lifecycle @cumulus/checksum@16.0.0~prepare: @cumulus/checksum@16.0.0

> @cumulus/checksum@16.0.0 prepare /home/zdy/Desktop/cumulus/packages/checksum
> npm run tsc

**_What is the problem?_**

**Comment by npauzenga** [comment]
Closing as the cumulus version mentioned is several versions old.
