### ISSUE TITLE
Skip DMR++ link publication to CMR

### ISSUE THREAD

**Issue by hailiangzhang** [nasa/cumulus#3665]
Hi,

There were some discussions were held regarding whether to publish the DMR++ link to CMR, and it's been decided not to include the DMR++ link for CMR publication. However, the DMR++ generation task will add the DMR++ link to the granule record, which will be utilized by the "update-granules-cmr-metadata-file-links" task to generate the CMR file, and then be published to CMR.

Although solutions exist to remove this DMR++ link before CMR publication, since this decision has already been made (presumably at the train level), we believe it would be beneficial if Cumulus could inherently skip DMR++ link publication to CMR. We propose that at the very least, the "update-granules-cmr-metadata-file-links" or "post-to-cmr" task should be configurable to skip DMR++ links.

**Comment by hailiangzhang** [comment]
It looks like the following PR may address this issue:
https://github.com/nasa/cumulus/pull/3791

**Comment by npauzenga** [comment]
Thanks @hailiangzhang. I'm going to close this issue but if there is conversation required, please create a Jira ticket and we'll prioritize.
