### ISSUE TITLE
CNM tasks getting delayed

### ISSUE THREAD

**Issue by hailiangzhang** [nasa/cumulus#3772]
At GES DISC, our CNM tasks are frequently delayed. The `sqsMessageConsumer` is supposed to run every minute, but CNM messages may not be dispatched for over 10 minutes.

**Comment by hailiangzhang** [comment]
I think this is because `sqsMessageConsumer` need fetch all the enabled rules to dispatch the CNM messages, but at GES DISC, we have a large number of rules (>8,000 in UAT), which causes 2 issues:
1. `sqsMessageConsumer` is taking too long to fetch all the enabled rules (~ 30 seconds out of the 1 min cron interval)
2. Database connection frequently failed due to large number of queries.

**Comment by paulpilone** [comment]
@hailiangzhang v18.3.4 has been released and includes this fix: https://github.com/nasa/cumulus/releases/tag/v18.3.4. Going to close this Issue.
