### ISSUE TITLE
Is this line missing a closing quotation mark?

### ISSUE THREAD

**Issue by hkryeung** [nasa/cumulus#3792]
https://github.com/nasa/cumulus/blob/2750792b9913f7bbad429d4b942ef4e59c5ef3d2/tf-modules/cumulus/ecs_cluster_instance_autoscaling_cf_template.yml.tmpl#L38

cc @jennyhliu

**Comment by jennyhliu** [comment]
Yes, thank you for reporting the issue @hkryeung

**Comment by Jkovarik** [comment]
Closing issue as fix was merged.
