### ISSUE TITLE
PDR Status Check Task failing with ExecutionDoesNotExist error

### ISSUE THREAD

**Issue by adtisdal-ASDC** [nasa/cumulus#3803]
The pdr-status-check task keeps failing with: `"Execution Does Not Exist: 'arn:aws:states:us-west-2:148260516034:execution:asdc2-sit-IngestUmmgGranule:907d07c5-face-4fb7-9e34-f876a7ec1f55'"`. I think we found the fix for it with just an update [here](https://github.com/nasa/cumulus/blob/master/tasks/pdr-status-check/index.js#L139)

**Comment by adtisdal-ASDC** [comment]
Here is the [PR](https://github.com/nasa/cumulus/pull/3804)

**Comment by npauzenga** [comment]
Thanks! There's a a PR in progress now that aims to address the line in question: https://github.com/nasa/cumulus/pull/3807/files#diff-ecaa6494fe31374c80ff1019a4248d9b16420657e471b311412b9601178f73e8

Once completed and reviewed, we'll slate it for release. Thanks!

**Comment by adtisdal-ASDC** [comment]
Thanks!

**Comment by npauzenga** [comment]
Above PR merged and available in https://github.com/nasa/cumulus/releases/tag/v19.1.0
