### ISSUE TITLE
Please update your aws CLI to latest version

### ISSUE THREAD

**Issue by jamesfwood** [nasa/cumulus#3875]
Inside of this file:

https://github.com/nasa/cumulus/blob/master/tf-modules/cumulus/ecs_cluster_instance_autoscaling_cf_template.yml.tmpl

You are using https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
Which is v1.  It's strongly recommended to update to v2 now.

Thank you!

**Comment by npauzenga** [comment]
Thanks @jamesfwood. We have a ticket currently being worked that removes the the LaunchConfiguration in favor of Launch Templates: https://bugs.earthdata.nasa.gov/browse/CUMULUS-3759. We try our best to monitor GH issues but our work is tracked via Jira so definitely feel free to create tickets there so we can prioritize effectively. 

I'm closing this issue in favor of the Jira ticket but will make a note to ensure the awscli packages is updated if it's still relevant.

Thanks again!
