### ISSUE TITLE
Non-working link in deployment documentation

### ISSUE THREAD

**Issue by colbyfayock** [nasa/cumulus#806]
Under the section describing where Cumulus packages are located, there's a link to a search on the npm website for `@cumulus`, but doesn't look like npm's search handles that correctly.

Perhaps using cumulus as a keyword would be more appropriate if everything is definitely tagged with it? https://www.npmjs.com/search?q=keywords:CUMULUS

https://nasa.github.io/cumulus/docs/deployment/deployment-readme#option-1-get-packages-from-npm

![image](https://user-images.githubusercontent.com/1045274/52733862-ceee5500-2f91-11e9-9771-1248e9cfa01d.png)

![image](https://user-images.githubusercontent.com/1045274/52733851-c6961a00-2f91-11e9-9243-03d38f11e046.png)

**Comment by laurenfrederick** [comment]
Thanks @colbyfayock. The fix for this is in master and will be released in version 1.11.2, anticipated today. In the meantime, you can use this link: https://www.npmjs.com/org/cumulus.
